data:
  data_root: data/SWAT
  dataset_only: SWAT
  meta_csv: null
  series: SWAT
  include: null

  window_size: 64
  step_size: 2
  normalize: zscore
  force_dim: null

training:
  save_dir: SWAT
  batch_size: 64
  num_epochs: 10
  num_workers: 4

  optimizer: adamw
  learning_rate: 0.0002       
  lr_g: null
  weight_decay: 0.0
  beta1: 0.5
  beta2: 0.999

  latent_dim: 26
  device: cuda
  amp: true
  no_cudnn: false

  seed: 42

  # 训练总损失
  w_recon: 1.0
  w_svdd: 1.0


  recon_loss_type: mse

  auto_balance_losses: false
  loss_ema_decay: 0.9
  log_interval: 100

  early_stop_patience: 2
  early_stop_min_delta: 0.0
  early_stop_warmup: 2
  early_stop_mode: min

testing:
  batch_size: 64
  num_workers: 4
  s_svdd: 1
  s_rec: 0
  auto_search_weights: false
  weight_search_n_div: 20
  rec_score_type: mse
